# Generated by Django 3.1.5 on 2021-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210604_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isLove',
            field=models.BooleanField(default=False),
        ),
    ]
