# Generated by Django 3.1.5 on 2021-07-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_islove'),
    ]

    operations = [
        migrations.AddField(
            model_name='pntoken',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
