# Generated by Django 3.1.5 on 2022-09-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_pntoken_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='stickId',
            new_name='stick_id',
        ),
    ]
