# Generated by Django 3.1.5 on 2022-09-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220917_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isLove',
            new_name='is_love',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sharedPhotos',
            new_name='shared_photos',
        ),
    ]
