# Generated by Django 3.1.5 on 2023-11-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20220917_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_love',
            new_name='is_like',
        ),
    ]
