
# Generated by Django 3.1.5 on 2021-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_userreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('A', 'Fake account'), ('B', 'Posting inappropriate things'), ('C', 'Harassment or Bullying'), ('Z', 'Something else')], max_length=1),
        ),
    ]
