# Generated by Django 3.1.5 on 2021-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20210611_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='fatal',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
