# Generated by Django 3.1.5 on 2021-06-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_error_fatal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='prev_route',
            new_name='route',
        ),
    ]
