# Generated by Django 3.1.5 on 2021-06-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20210624_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='fatal',
            new_name='isFatal',
        ),
    ]
