# Generated by Django 3.1.5 on 2021-06-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0008_auto_20210624_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('A', 'Fake account'), ('B', 'Posting inappropriate things'), ('C', 'Harassment or Bullying'), ('Z', 'Something else')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_post_reports', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_post_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
