# Generated by Django 3.1.5 on 2021-06-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_note_loves'),
        ('support', '0009_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='photos.image'),
        ),
    ]
