# Generated by Django 3.1.5 on 2022-08-17 10:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20220719_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uri', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/omar/dev/sticknet-engine/public/PDFs'), upload_to='messages/audio/')),
            ],
        ),
    ]
