# Generated by Django 3.1.5 on 2022-08-27 13:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0013_publicfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicfile',
            name='uri',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/public/', location='/Users/omar/dev/sticknet-engine/public'), upload_to='PDFs/'),
        ),
    ]
