# Generated by Django 3.1.5 on 2022-09-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_auto_20220827_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='isFatal',
            new_name='is_fatal',
        ),
    ]
