# Generated by Django 3.1.5 on 2023-03-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
