# Generated by Django 3.1.5 on 2023-07-14 08:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_delete_somemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='uri',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/public/', location='/public/'), upload_to='PDFs/'),
        ),
    ]
