# Generated by Django 3.1.5 on 2023-07-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='vault.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='is_home_folder',
            field=models.BooleanField(default=False),
        ),
    ]
