# Generated by Django 3.1.5 on 2023-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20230728_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cipher',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
