# Generated by Django 3.1.5 on 2023-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_file_cipher'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uri_key',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
