# Generated by Django 3.1.5 on 2023-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_file_uri_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview_file_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='preview_uri_key',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='cipher',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
