# Generated by Django 3.1.5 on 2023-08-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_auto_20230816_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uri',
        ),
    ]
