# Generated by Django 3.1.5 on 2023-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_remove_file_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='previewCipher',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
