# Generated by Django 3.1.5 on 2023-08-20 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0010_auto_20230817_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VaultAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_key', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('preview_uri_key', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('preview_file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview_cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='vault.vaultalbum')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
