# Generated by Django 3.1.5 on 2023-08-20 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0012_auto_20230820_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='vault.vaultalbum'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
