# Generated by Django 3.1.5 on 2023-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_auto_20230820_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='photo_only',
            field=models.BooleanField(default=False),
        ),
    ]
