# Generated by Django 3.1.5 on 2023-08-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_file_photo_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='photo_only',
        ),
    ]
