# Generated by Django 3.1.5 on 2023-08-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_remove_file_photo_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_home_folder',
        ),
        migrations.AddField(
            model_name='file',
            name='folder_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('home', 'Home'), ('camera_uploads', 'Camera Uploads')], default='normal', max_length=20),
        ),
    ]
