# Generated by Django 3.1.5 on 2023-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_auto_20230829_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
