# Generated by Django 3.1.5 on 2023-09-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0019_auto_20230830_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
