# Generated by Django 3.1.5 on 2023-09-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0022_vaultnote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='file',
            name='width',
            field=models.IntegerField(default=1000),
        ),
    ]
