# Generated by Django 3.1.5 on 2023-09-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_auto_20230924_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
