# Generated by Django 3.1.5 on 2023-09-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0025_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, default='image', max_length=20, null=True),
        ),
    ]
