# Generated by Django 3.1.5 on 2023-11-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0028_auto_20230928_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaultnote',
            old_name='text',
            new_name='cipher',
        ),
    ]
