# Generated by Django 3.1.5 on 2023-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0030_auto_20231121_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
