# Generated by Django 3.1.5 on 2024-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0031_auto_20231121_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='preview_uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
