# Generated by Django 3.1.5 on 2024-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0032_auto_20240225_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
