# Generated by Django 3.1.5 on 2021-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='resizeMode',
            field=models.CharField(blank=True, default='cover', max_length=100, null=True),
        ),
    ]
