# Generated by Django 3.1.5 on 2021-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilepicture_resizemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecover',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profilecover',
            name='width',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='width',
            field=models.IntegerField(default=1000),
        ),
    ]
