# Generated by Django 3.1.5 on 2021-06-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='favoritesIds',
        ),
    ]
