# Generated by Django 3.1.5 on 2021-06-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210622_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='just_added_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='just_removed_groups',
        ),
    ]
