# Generated by Django 3.1.5 on 2021-07-05 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favoritesIds',
        ),
        migrations.AddField(
            model_name='preferences',
            name='favoritesIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
