# Generated by Django 3.1.5 on 2021-07-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210705_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='chatId',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
