# Generated by Django 3.1.5 on 2021-07-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210714_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='changing_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_trials',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_code',
        ),
        migrations.AddField(
            model_name='user',
            name='passwordTrials',
            field=models.IntegerField(default=0),
        ),
    ]
