# Generated by Django 3.1.5 on 2021-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210717_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordBlockTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
