# Generated by Django 3.1.5 on 2021-11-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20210718_1002'),
        ('users', '0017_device_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatBackup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatBackup', to='groups.cipher'),
        ),
    ]
