# Generated by Django 3.1.5 on 2021-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_chatbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backupFreq',
            field=models.CharField(blank=True, choices=[('never', 'never'), ('weekly', 'weekly')], max_length=20, null=True),
        ),
    ]
