# Generated by Django 3.1.5 on 2022-07-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220717_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donationReminder',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
