# Generated by Django 3.1.5 on 2022-07-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_donationreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minViableVersion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
