# Generated by Django 3.1.5 on 2022-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_appsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='minViableVersion',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='minViableAndroidVersion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='minViableIOSVersion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
