# Generated by Django 3.1.5 on 2022-09-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220805_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='donationReminder',
            new_name='donation_reminder',
        ),
    ]
