# Generated by Django 3.1.5 on 2022-09-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220917_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwordKey',
            new_name='password_key',
        ),
    ]
