# Generated by Django 3.1.5 on 2022-09-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20210718_1002'),
        ('users', '0029_auto_20220917_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='backupFreq',
            new_name='backup_freq',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='highlightsIds',
            new_name='highlights_ids',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='websiteLink',
            new_name='website_link',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='chatBackup',
            new_name='chat_backup',
        ),
    ]
