# Generated by Django 3.1.5 on 2022-09-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20210718_1002'),
        ('users', '0030_auto_20220917_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_backup', to='groups.cipher'),
        ),
    ]
