# Generated by Django 3.1.5 on 2022-09-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20220917_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='finishedRegistration',
            new_name='finished_registration',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hiddenImages',
            new_name='hidden_images',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='localId',
            new_name='local_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nextPreKeyId',
            new_name='next_pre_key_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='oneTimeId',
            new_name='one_time_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwordBlockTime',
            new_name='password_block_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwordSalt',
            new_name='password_salt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwordTrials',
            new_name='password_trials',
        ),
    ]
