# Generated by Django 3.1.5 on 2022-09-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220917_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='backup_freq',
            new_name='backup_frequency',
        ),
    ]
