# Generated by Django 3.1.5 on 2022-09-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20220917_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecover',
            old_name='fileSize',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='profilepicture',
            old_name='fileSize',
            new_name='file_size',
        ),
    ]
