# Generated by Django 3.1.5 on 2022-09-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20220917_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecover',
            old_name='stickId',
            new_name='stick_id',
        ),
        migrations.RenameField(
            model_name='profilepicture',
            old_name='stickId',
            new_name='stick_id',
        ),
    ]
