# Generated by Django 3.1.5 on 2022-09-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20220917_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='chatId',
            new_name='chat_id',
        ),
    ]
