# Generated by Django 3.1.5 on 2022-09-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220917_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='authToken',
            new_name='auth_token',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceId',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='chatDevice',
            new_name='chat_device',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='favoritesIds',
            new_name='favorites_ids',
        ),
        migrations.RenameField(
            model_name='profilecover',
            old_name='resizeMode',
            new_name='resize_mode',
        ),
        migrations.RenameField(
            model_name='profilepicture',
            old_name='resizeMode',
            new_name='resize_mode',
        ),
    ]
