# Generated by Django 3.1.5 on 2022-09-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20220917_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=44, null=True, unique=True),
        ),
    ]
