# Generated by Django 3.1.5 on 2022-09-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_phone_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
    ]
