# Generated by Django 3.1.5 on 2023-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whitelist_premium',
            field=models.BooleanField(default=False),
        ),
    ]
