# Generated by Django 3.1.5 on 2023-08-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_whitelist_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_used',
            field=models.IntegerField(default=0),
        ),
    ]
