# Generated by Django 3.1.5 on 2023-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_user_storage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='photo_backup_setting',
            field=models.CharField(choices=[('all', 'all'), ('new', 'new')], default='all', max_length=10),
        ),
    ]
