# Generated by Django 3.1.5 on 2023-09-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_email_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_code',
        ),
    ]
