# Generated by Django 3.1.5 on 2023-09-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitedaccesstoken',
            old_name='phone',
            new_name='auth_id',
        ),
    ]
