# Generated by Django 3.1.5 on 2023-10-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_user_subpendingcancellation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subPendingCancellation',
            new_name='subscription_expiring',
        ),
    ]
