# Generated by Django 3.1.5 on 2023-11-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20231021_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_profile_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_profile_picture', to='users.profilepicture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_picture', to='users.profilepicture'),
        ),
    ]
