# Generated by Django 3.1.5 on 2023-11-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20231122_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='self_profile_picture',
        ),
    ]
