# Generated by Django 3.1.5 on 2023-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_remove_user_self_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='self_cipher',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='self_uri',
            field=models.FileField(blank=True, null=True, upload_to='SelfProfilePictures/'),
        ),
    ]
