# Generated by Django 3.1.5 on 2023-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20231122_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='self_cipher',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
