# Generated by Django 3.1.5 on 2023-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20231122_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='folder_icon',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('orange', 'orange')], max_length=10, null=True),
        ),
    ]
