# Generated by Django 3.1.5 on 2023-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_preferences_folder_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(blank=True, choices=[('ios', 'ios'), ('android', 'android')], max_length=10, null=True),
        ),
    ]
