# Generated by Django 3.1.5 on 2024-01-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
    ]
