# Generated by Django 3.1.5 on 2024-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_remove_user_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='added_connections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='donation_reminder',
        ),
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'rgb(255,0,0)'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange'), ('purple', 'purple'), ('limegreen', 'limegreen'), ('deeppink', 'deeppink'), ('darkred', 'darkred'), ('deepskyblue', 'deepskyblue'), ('mediumpurple', 'mediumpurple')], max_length=20, null=True),
        ),
    ]
