# Generated by Django 3.1.5 on 2024-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20240207_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecover',
            name='uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='self_uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
