# Generated by Django 3.1.5 on 2024-02-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20240225_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='storage_used',
            new_name='vault_storage',
        ),
    ]
