# Generated by Django 3.1.5 on 2024-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20240225_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_storage',
            field=models.IntegerField(default=0),
        ),
    ]
