# Generated by Django 3.1.5 on 2024-02-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_user_chat_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecover',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilecover',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='preview_cipher',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='preview_file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='preview_uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
