# Generated by Django 3.1.5 on 2024-06-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20240227_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='vault_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
