# Generated by Django 3.1.5 on 2024-12-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20240617_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereum_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
