# Generated by Django 3.1.5 on 2024-12-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_user_ethereum_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_secret',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
