# Generated by Django 3.1.5 on 2024-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_user_account_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethereum_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
