# Generated by Django 3.1.5 on 2024-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20241225_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_secret',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
    ]
