# Generated by Django 3.1.5 on 2024-12-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20241226_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='web_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
