# Generated by Django 3.1.5 on 2023-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0002_transaction_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.CharField(choices=[('com.stiiick.premium.1', 'sqaure')], default='com.stiiick.premium.1', max_length=100),
        ),
    ]
