# Generated by Django 3.1.5 on 2023-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0003_auto_20230319_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.CharField(choices=[('com.stiiick.premium.1', 'Sticknet Premium (monthly)')], default='com.stiiick.premium.1', max_length=100),
        ),
    ]
