# Generated by Django 3.1.5 on 2023-03-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0004_auto_20230319_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expires_date_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_date_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
