# Generated by Django 3.1.5 on 2023-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0005_auto_20230319_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.CharField(choices=[('com.stiiick.premium.1', 'Sticknet Premium (monthly)')], max_length=100, null=True),
        ),
    ]
