# Generated by Django 3.1.5 on 2023-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0006_auto_20230319_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='platform',
            field=models.CharField(choices=[('I', 'ios'), ('A', 'android')], max_length=1, null=True),
        ),
    ]
