# Generated by Django 3.1.5 on 2023-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0007_transaction_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
