# Generated by Django 3.1.5 on 2023-03-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0009_auto_20230319_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, null=True),
        ),
    ]
