# Generated by Django 3.1.5 on 2023-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0010_auto_20230319_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(),
        ),
    ]
