# Generated by Django 3.1.5 on 2023-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0011_auto_20230319_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
