# Generated by Django 3.1.5 on 2023-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0014_auto_20230430_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, null=True),
        ),
    ]
