# Generated by Django 3.1.5 on 2023-10-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0015_auto_20231018_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription_id',
            field=models.CharField(max_length=56, null=True, unique=True),
        ),
    ]
