# Generated by Django 3.1.5 on 2023-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0016_transaction_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
