# Generated by Django 3.1.5 on 2023-12-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0017_auto_20231202_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
