# Generated by Django 3.1.5 on 2023-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0018_auto_20231202_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.CharField(choices=[('com.stiiick.premium.1', 'Sticknet Premium (monthly)')], max_length=100, null=True),
        ),
    ]
