# Generated by Django 3.1.5 on 2021-06-04 11:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUri', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('uri', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('audioUri', models.FileField(blank=True, null=True, upload_to='audio/images/')),
                ('audioDuration', models.FloatField(default=0)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('youtube', models.CharField(blank=True, max_length=1000, null=True)),
                ('youtubeThumbnail', models.CharField(blank=True, max_length=1000, null=True)),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('S', 'square'), ('V', 'vertical'), ('H', 'horizontal'), ('C', 'contain')], default='S', max_length=1)),
                ('duration', models.FloatField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('thumbCipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('audioCipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('stickId', models.CharField(max_length=100)),
                ('partyId', models.CharField(max_length=100)),
                ('fileSize', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
                ('index', models.IntegerField(default=1)),
                ('ofTotal', models.IntegerField(default=1)),
                ('isProfile', models.BooleanField(default=False)),
                ('shareExt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.FileField(blank=True, null=True, upload_to='test/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.CharField(blank=True, max_length=10000)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/comments/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('sketch', models.FileField(blank=True, upload_to='sketches/')),
                ('isReply', models.BooleanField(default=False)),
                ('cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('fileSize', models.IntegerField(default=0)),
                ('stickId', models.CharField(blank=True, max_length=100, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_notes', to='photos.album')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='photos.image')),
                ('replies', models.ManyToManyField(blank=True, related_name='parent_note', to='photos.Note')),
            ],
        ),
    ]
