# Generated by Django 3.1.5 on 2021-06-14 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_auto_20210613_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loved_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
