# Generated by Django 3.1.5 on 2021-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_note_loves'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='textPhoto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
