# Generated by Django 3.1.5 on 2022-07-10 08:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_textphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uris',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='photos/'), blank=True, null=True, size=None),
        ),
    ]
