# Generated by Django 3.1.5 on 2022-07-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_image_uris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uris',
        ),
    ]
