# Generated by Django 3.1.5 on 2022-07-10 08:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_image_uris'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('videoUri', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('size', models.CharField(choices=[('S', 'square'), ('V', 'vertical'), ('H', 'horizontal'), ('C', 'contain')], default='S', max_length=1)),
                ('duration', models.FloatField(default=0)),
                ('width', models.IntegerField(default=1000)),
                ('height', models.IntegerField(default=1000)),
                ('cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('thumbCipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('fileSize', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='photos.image')),
            ],
        ),
    ]
