# Generated by Django 3.1.5 on 2022-07-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='album_cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blob_cover', to='photos.album'),
        ),
    ]
