# Generated by Django 3.1.5 on 2022-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_blob_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='textPhoto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
