# Generated by Django 3.1.5 on 2022-07-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_blob_textphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='textPhoto',
        ),
    ]
