# Generated by Django 3.1.5 on 2022-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_blob_textphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blob',
            name='youtubeThumbnail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
