# Generated by Django 3.1.5 on 2022-07-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20220712_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='youtubeThumbnail',
        ),
    ]
