# Generated by Django 3.1.5 on 2022-09-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_auto_20220712_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blob',
            old_name='fileSize',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='fileSize',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='isProfile',
            new_name='is_profile',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='ofTotal',
            new_name='of_total',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='shareExt',
            new_name='share_ext',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='fileSize',
            new_name='file_size',
        ),
    ]
