# Generated by Django 3.1.5 on 2022-09-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20220917_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='partyId',
            new_name='party_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='stickId',
            new_name='stick_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='stickId',
            new_name='stick_id',
        ),
    ]
