# Generated by Django 3.1.5 on 2022-09-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20220917_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blob',
            old_name='textPhoto',
            new_name='text_photo',
        ),
        migrations.RenameField(
            model_name='blob',
            old_name='thumbCipher',
            new_name='thumb_cipher',
        ),
        migrations.RenameField(
            model_name='blob',
            old_name='videoUri',
            new_name='video_uri',
        ),
        migrations.RenameField(
            model_name='blob',
            old_name='youtubeThumbnail',
            new_name='youtube_thumbnail',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='audioCipher',
            new_name='audio_cipher',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='audioDuration',
            new_name='audio_duration',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='audioUri',
            new_name='audio_uri',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='textPhoto',
            new_name='text_photo',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='thumbCipher',
            new_name='thumb_cipher',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='videoUri',
            new_name='video_uri',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='youtubeThumbnail',
            new_name='youtube_thumbnail',
        ),
    ]
