# Generated by Django 3.1.5 on 2022-09-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_auto_20220917_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='isReply',
            new_name='is_reply',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='replyTo',
            new_name='reply_to',
        ),
    ]
