# Generated by Django 3.1.5 on 2023-09-09 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0019_auto_20220917_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='image_seen_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='image_loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
