# Generated by Django 3.1.5 on 2023-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_auto_20230909_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='thumbnail_uri_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blob',
            name='uri_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='uri_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
