# Generated by Django 3.1.5 on 2023-11-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_auto_20230914_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blob',
            old_name='thumbnail_uri_key',
            new_name='preview_uri_key',
        ),
    ]
