# Generated by Django 3.1.5 on 2023-11-30 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0022_auto_20231129_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='loves',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='loves',
        ),
        migrations.RemoveField(
            model_name='note',
            name='loves',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
