# Generated by Django 3.1.5 on 2024-03-12 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0020_group_storage'),
        ('stick_protocol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_key', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('preview_uri_key', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('preview_file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('is_album_cover', models.BooleanField(default=False)),
                ('cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview_cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('stick_id', models.CharField(max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_files', to='groups.group')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_files', to='stick_protocol.party')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_key', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('stick_id', models.CharField(max_length=100)),
                ('cipher', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_audios', to='groups.group')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_audios', to='stick_protocol.party')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_count', models.IntegerField(default=0)),
                ('videos_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auto_month', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_albums', to='groups.group')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_albums', to='stick_protocol.party')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_albums', to='groups.cipher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_albums', to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
