# Generated by Django 3.1.5 on 2024-03-12 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0020_group_storage'),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfile',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatalbum'),
        ),
    ]
