# Generated by Django 3.1.5 on 2024-06-17 06:03

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_group_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20240312_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
