# Generated by Django 3.1.5 on 2021-06-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('uri', models.FileField(blank=True, null=True, upload_to='CipherFiles/')),
                ('fileSize', models.IntegerField(blank=True, default=0, null=True)),
                ('stickId', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('chatId', models.CharField(max_length=1000, unique=True)),
                ('verificationId', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkEnabled', models.BooleanField(default=False)),
                ('linkApproval', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stickId', models.CharField(max_length=100)),
                ('uri', models.FileField(upload_to='GroupsCovers/')),
                ('resizeMode', models.CharField(default='cover', max_length=100)),
                ('cipher', models.CharField(max_length=1000)),
                ('fileSize', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempDisplayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stickId', models.CharField(max_length=100)),
                ('cipher', models.CharField(max_length=1000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
