# Generated by Django 3.1.5 on 2021-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210604_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcover',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='groupcover',
            name='width',
            field=models.IntegerField(default=1000),
        ),
    ]
