# Generated by Django 3.1.5 on 2021-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20210703_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='textLength',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
