# Generated by Django 3.1.5 on 2021-07-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0007_cipher_textlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdisplayname',
            name='user',
        ),
        migrations.AddField(
            model_name='tempdisplayname',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tdn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempdisplayname',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tdn', to=settings.AUTH_USER_MODEL),
        ),
    ]
