# Generated by Django 3.1.5 on 2022-09-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20220917_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cipher',
            old_name='textLength',
            new_name='text_length',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='chatId',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='linkApproval',
            new_name='link_approval',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='linkEnabled',
            new_name='link_enabled',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='verificationId',
            new_name='verification_id',
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_ids', to='groups.cipher'),
        ),
    ]
