# Generated by Django 3.1.5 on 2022-09-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20220917_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_links', to='groups.cipher'),
        ),
    ]
