# Generated by Django 3.1.5 on 2022-09-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20220917_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcover',
            old_name='resizeMode',
            new_name='resize_mode',
        ),
    ]
