# Generated by Django 3.1.5 on 2023-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20220917_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
