# Generated by Django 3.1.5 on 2024-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_group_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcover',
            name='uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
