# Generated by Django 3.1.5 on 2024-02-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_groupcover_uri_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcover',
            name='preview_cipher',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='groupcover',
            name='preview_file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupcover',
            name='preview_uri_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
