# Generated by Django 3.1.5 on 2024-02-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_auto_20240227_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcover',
            name='preview_cipher',
        ),
        migrations.RemoveField(
            model_name='groupcover',
            name='preview_file_size',
        ),
        migrations.RemoveField(
            model_name='groupcover',
            name='preview_uri_key',
        ),
    ]
