# Generated by Django 3.1.5 on 2024-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_auto_20240227_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcover',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupcover',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
