# Generated by Django 3.1.5 on 2024-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_auto_20240227_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='storage',
            field=models.IntegerField(default=0),
        ),
    ]
